// Code generated by locgen. DO NOT EDIT.

package localization

type MessageKey string

var Messages = struct {
	admin struct {
		callback struct {
			Approved MessageKey
			Rejected MessageKey
		}
		new_message struct {
			Message_header MessageKey
			Approve_button MessageKey
			Reject_button  MessageKey
		}
	}
	user struct {
		Message_received MessageKey
	}
	commands struct {
		Start MessageKey
		Help  MessageKey
	}
}{
	admin: struct {
		callback struct {
			Approved MessageKey
			Rejected MessageKey
		}
		new_message struct {
			Message_header MessageKey
			Approve_button MessageKey
			Reject_button  MessageKey
		}
	}{
		callback: struct {
			Approved MessageKey
			Rejected MessageKey
		}{
			Approved: "messages.admin.callback.approved",
			Rejected: "messages.admin.callback.rejected",
		},
		new_message: struct {
			Message_header MessageKey
			Approve_button MessageKey
			Reject_button  MessageKey
		}{
			Message_header: "messages.admin.new_message.message_header",
			Approve_button: "messages.admin.new_message.approve_button",
			Reject_button:  "messages.admin.new_message.reject_button",
		},
	},
	user: struct {
		Message_received MessageKey
	}{
		Message_received: "messages.user.message_received",
	},
	commands: struct {
		Start MessageKey
		Help  MessageKey
	}{
		Start: "messages.commands.start",
		Help:  "messages.commands.help",
	},
}
