// Code generated by locgen. DO NOT EDIT.

package locales

type MessageKey string

var (
	Errors = struct {
	}{}

	Messages = struct {
		Admin struct {
			Callback struct {
				Approved MessageKey
				Rejected MessageKey
			}
			NewMessage struct {
				MessageHeader MessageKey
				ApproveButton MessageKey
				RejectButton  MessageKey
			}
		}
		User struct {
			MessageReceived MessageKey
		}
		Commands struct {
			Help  MessageKey
			Start MessageKey
		}
	}{
		Admin: struct {
			Callback struct {
				Approved MessageKey
				Rejected MessageKey
			}
			NewMessage struct {
				MessageHeader MessageKey
				ApproveButton MessageKey
				RejectButton  MessageKey
			}
		}{
			Callback: struct {
				Approved MessageKey
				Rejected MessageKey
			}{
				Approved: "messages.admin.callback.approved",
				Rejected: "messages.admin.callback.rejected",
			},
			NewMessage: struct {
				MessageHeader MessageKey
				ApproveButton MessageKey
				RejectButton  MessageKey
			}{
				MessageHeader: "messages.admin.new_message.message_header",
				ApproveButton: "messages.admin.new_message.approve_button",
				RejectButton:  "messages.admin.new_message.reject_button",
			},
		},
		User: struct {
			MessageReceived MessageKey
		}{
			MessageReceived: "messages.user.message_received",
		},
		Commands: struct {
			Help  MessageKey
			Start MessageKey
		}{
			Help:  "messages.commands.help",
			Start: "messages.commands.start",
		},
	}
)
