name: Build and Push to Yandex Container Registry

on:
  push:
    branches:
      - main  # Запускать workflow только при пуше в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_IAM_TOKEN }}" | docker login --username iam --password-stdin cr.yandex

      - name: Build and push Docker image
        run: |
          docker build --file ./.build/Dockerfile -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/menopause-tg-bot:latest .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/menopause-tg-bot:latest